# UK ETA Gateway - Production Supabase Configuration

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation_enabled = true

[auth]
enabled = true
port = 54328

[auth.email]
enable_signup = false  # Disable public signup for production
double_confirm_changes = true
enable_confirmations = true

# Production-specific auth settings
[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[edge_runtime]
enabled = true
port = 54329

# Production Edge Function settings
[functions]
verify_jwt = true

# Production logging
[analytics]
enabled = true

# Production-specific feature flags
[experimental]
enabled = false